/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fecha_hora.h"

bool_t
obtener_tiempo_servidor_1_svc(cadena user, cadena op, cadena tiempo, int *result,  struct svc_req *rqstp)
{
	bool_t retval;
	retval = TRUE;
	/*
	 * insert server code here
	 */

	 printf("%s    %s    %s\n", user, op, tiempo);

	return retval;
}

int
obtener_tiempo_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
